services:
    _defaults:
        autowire: true
        autoconfigure: true
    ICS\SocialnetworkBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    ICS\SocialnetworkBundle\Twig\:
        resource: "../src/Twig"
        public: false
        tags: ['twig.extension']